Output ../ks-ctx-cmd-demo.gif

Set Shell "bash"
Set FontSize 16
Set Width 1200
Set Height 550

Sleep 1s
Type "kubesnap ctx"
Sleep 500ms
Enter
Sleep 1s

Down
Sleep 500ms
Down
Sleep 500ms
Enter
Sleep 3s

Type "kubesnap ctx"
Sleep 500ms
Enter
Sleep 500ms
Down
Sleep 1s
Type "r"
Sleep 1s

Type "-rename"
Sleep 500ms
Enter
Sleep 1s

Type "kubesnap ctx"
Sleep 500ms
Enter
Sleep 1s

Type "d"
Sleep 500ms
Down
Space
Sleep 500ms
Down
Space
Sleep 500ms
Up
Space
Sleep 500ms

Enter

Sleep 500ms
Type "yes"
Sleep 500ms
Enter

Sleep 3s
